In [ ]:
import numpy as np

In [12]:
arr = np.array([1,2,3,4])
print(arr)

matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


In [8]:
#Special Arrays

zeros = np.zeros((2,3))
ones = np.ones((3,3))
arange = np.arange(0,10,2)
linspace = np.linspace(0,1,10)
identity = np.eye(4)

print(zeros)
print(ones)
print(arange)
print(linspace)
print(identity)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
print(arr.shape) #dimensions
print(arr.ndim) # number of dimensions
print(arr.size) # total number of elements
print(arr.dtype) # data type

(4,)
1
4
int64


In [5]:
#Slicing
a = np.array([10,20,30,40,50])
print(a[0]) #first element
print(a[-1]) #last element
print(a[1:4]) #slicing

b = np.array([[1,2,3],[4,5,6]])
print(b[0,2]) #row 0 , col 2
print(b[:,1]) # all rows, col 1

10
50
[20 30 40]
3
[2 5]


In [9]:
#Create an 2D aray of dim 3x3
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
# print(mat)
print(mat[1,0])
print(mat[:,2])
print(mat[1,:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
4
[3 6 9]
[4 5 6]


In [12]:
x = np.array([1,2,3])
y = np.array([10,20,30])

print(x+y)
print(x*y)
print(x**2)

print(np.sqrt(x))
print(np.exp(x))
print(np.sin(x))

[11 22 33]
[10 40 90]
[1 4 9]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.84147098 0.90929743 0.14112001]


In [15]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,1],[1,1],[1,1]])

print(a @ b) #multiplication
print(np.dot(a,b)) #dot product
print(a.T) #transpose

[[ 6  6]
 [15 15]]
[[ 6  6]
 [15 15]]
[[1 4]
 [2 5]
 [3 6]]


In [16]:
arr = np.array([1,2,3,4,5])

print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.std())

15
3.0
5
1
1.4142135623730951


In [21]:
arr = np.arange(1,13)
reshaped = arr.reshape(6,2)
print(reshaped)

flattend = reshaped.flatten()
print(flattend)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [23]:
print(np.random.rand(3))
print(np.random.randint(1,10,5)) #(start, stop, total numbers to be generated)
print(np.random.randn(2,3)) #mat of size 2x3

[0.64518331 0.36599871 0.00878095]
[3 6 4 6 1]
[[ 0.79002149 -0.33411261  1.02991197]
 [-0.08441395 -0.73308452 -0.24126997]]


In [24]:
#Convert to Float
arr_float = arr.astype(float)
print("Converted to float: ", arr_float)
print("Data type: ", arr_float.dtype)

Converted to float:  [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
Data type:  float64


In [29]:
#Take marks as input(0-100) of elif else t0 print the grade

marks = int(input())
if marks>=90 and marks<=100:
    print("Grade: A")
elif marks>=75 and marks<=89:
    print("Grade: B")
elif marks>=50 and marks<=74:
    print("Grade: C")
else:
    print("Grade: Fail")

50
Grade: C


In [31]:
#Accept a number from the user and use a while loop to find the sum of its digit

num = int(input())
sum = 0
while num>0:
    sum+=num%10
    num//=10
print(sum)

253
10


In [36]:
#Write a function isPrime(n) that returns True if a number is prime, otherwise False. Test if for multiple values

def isPrime(n):
    count=0
    for num in range(1,n+1):
        if n%num==0:
            count+=1
    print("Prime") if count==2 else print("Not Prime")
isPrime(int(input()))

6
Not Prime


In [48]:
#Palindrome or Not??
str = input()
reversed_str = str[::-1]
print("Palindrome") if str==reversed_str else print("Not Palindrome")

taat
Palindrome


In [56]:
#Create 2 3x3 matrix and perform
# a.Matrix multiplication
# b.Determinant of a matrix
# c.Inverse of a matrix
# Verfiy that multiplying a matrix with its inverse gives identity matrix

mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat_multiplication = mat1 @ mat2
mat_determinant = np.linalg.det(mat1).round()
mat_inverse = np.linalg.inv(mat1).round()
print(mat_multiplication)
print(mat_determinant)
print(mat_inverse)

print(mat1 @ mat_inverse)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
-0.0
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
[[ 0.  1. -2.]
 [ 0.  2. -4.]
 [ 0.  3. -2.]]


In [59]:
# Suppose you have exam marks of 10 students stored in a python list 
# Convert it into numpy array and compute 
# a. Average marks of the class
# b. Students who scored above average

arr = list(map(int,input().split()))
np_arr = np.array(arr)
print(np.mean(np_arr))
for mark in np_arr:
    if mark>np.mean(np_arr):
        print(mark, end=" ")

10 20 30 40 50 60 70 80 90 100
55.0
60 70 80 90 100 